name: "New Relic Deployment Marker"
description: "Send deployment marker to New Relic via NerdGraph"
author: "Your Team"

inputs:
  api_key:
    description: "New Relic User API Key (not ingest key)"
    required: true
  app_id:
    description: "New Relic Entity GUID"
    required: true
  revision:
    description: "Git SHA or version identifier"
    required: true
  user:
    description: "User or actor triggering the deployment"
    required: true
  description:
    description: "Deployment description"
    required: false
    default: "GitHub Actions Deployment"

runs:
  using: "composite"
  steps:
    - name: Send deployment marker to New Relic
      shell: bash
      run: |
        curl -X POST https://api.newrelic.com/graphql \
          -H "Content-Type: application/json" \
          -H "API-Key: ${{ inputs.api_key }}" \
          -d '{
            "query": "mutation { changeTrackingCreateDeployment(deployment: {version: \"${{ inputs.revision }}\", entityGuid: \"${{ inputs.app_id }}\", description: \"${{ inputs.description }}\", user: \"${{ inputs.user }}\"}) { deploymentId } }"
          }'
