name: Deploy and Notify New Relic

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # 🔧 Simulate a deployment step
      - name: Simulate deployment
        run: echo "Deploying your app..."

      # 🚀 Notify New Relic using your pipeline extension
      - name: Send New Relic Deployment Marker
        uses: ./.github/actions/newrelic-deploy-marker
        with:
          api_key: ${{ secrets.NEW_RELIC_API_KEY }}
          app_id: ${{ secrets.NEW_RELIC_APP_ID }}
          revision: ${{ github.sha }}
          user: ${{ github.actor }}
          description: "Auto-deploy from GitHub Actions"

