name: Deploy and Notify New Relic

on:
  push:
    branches:
      - main

permissions:
  contents: read  # 👈 Needed for actions/checkout to succeed

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Simulate deployment
        run: echo "Deploying your app..."

      - name: Send New Relic Deployment Marker
        uses: ./.github/actions/newrelic-deploy-marker
        with:
          api_key: ${{ secrets.NEW_RELIC_API_KEY }}
          app_id: ${{ secrets.NEW_RELIC_APP_ID }}
          revision: ${{ github.sha }}
          user: ${{ github.actor }}
          description: "Auto-deploy from GitHub Actions"
